kind: Pod
apiVersion: v1
metadata:
  name: hostpath-provisioner
spec:
  containers:
    - name: hostpath-provisioner
      image: mazdermind/hostpath-provisioner
      imagePullPolicy: "IfNotPresent"
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName

            - name: PV_DIR
              value: /var/kubernetes

#            - name: PV_RECLAIM_POLICY
#              value: Retain

      volumeMounts:
        - name: pv-volume
          mountPath: /var/kubernetes

  volumes:
    - name: pv-volume
      hostPath:
        path: /var/kubernetes
