kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hostpath-test-claim
#  annotations:
#    volume.beta.kubernetes.io/storage-class: "hostpath"
spec:
  storageClassName: "hostpath"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
